### ISSUE TITLE
moment.duration(...).format is not a function thrown

### ISSUE THREAD

**Issue by markusguenther** [DevExpress/testcafe-reporter-spec#3]
I updated moment js in my project to the latest version 2.19.3 and since then I get the error message

```
this.moment.duration(...).format is not a function
```

Localized that the error comes from testcafe-reporter-list and testcafe-reporter-spec.
Adjusted that for me to fix that and hope that the PR finds the way into the library.

```
var durationStr = this.moment.utc(this.moment.duration(durationMs).asMilliseconds()).format('H[h] mm[m] ss[s]');
```

**Comment by AndreyBelym** [comment]
This issue is fixed in `testcafe@0.23.0`: https://github.com/DevExpress/testcafe/commit/51840b05fc4a2621a7d5c88933a00ca1f8e3ff0c. Feel free to reopen the issue if you still can reproduce the problem in the actual TestCafe version.
