### ISSUE TITLE
How to change test JSON files

### ISSUE THREAD

**Issue by nivnahmias** [DevExpress/testcafe-reporter-spec#5]
I forked this repo in order to add execution time per test but i can't seem to get the tests running.
My main issue is trying to update the json test files, i can't get the outputs to match and editing the JSON is very hard.

Is there a simpler way around this? can I save the new report's output in JSON format with ANSII escape characters somehow and just replace the test data?

**Comment by AndreyBelym** [comment]
Hi @nivnahmias, you can use [TestCafe API](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/) and override methods of `process.stdout` to redirect reporter's output to a variable, and then use `JSON.stringify` and `fs.writeFileSync` to save it as a content of a JSON file:
```js
const fs = require('fs');
const testcafe = require('testcafe');

let reporterOutput = '';

process.stdout.write = data => reporterOutput += data;
process.stdout.end = data => reporterOutput += data;

testcafe()
    .then(t => { 
        global.t = t;

        return t
            .createRunner()
            .src('test.js')
            .browsers('chrome')
            .run();
    })
    .then(() => {
        fs.writeFileSync('test.log', JSON.stringify(reporterOutput));
        return global.t.close();
    });
```

**Comment by nivnahmias** [comment]
Thanks, using fs did the trick!
